[colors]
foreground=EBDBB2
background=282828

regular0=282828  # black
regular1=CC241D  # red
regular2=98971A  # green
regular3=D79921  # yellow
regular4=458588  # blue
regular5=B16286  # magenta
regular6=689D6A  # cyan
regular7=A89984  # white

bright0=928374  # bright black
bright1=FB4934  # bright red
bright2=B8BB26  # bright green
bright3=FABD2F  # bright yellow
bright4=83A598  # bright blue
bright5=D3869B  # bright magenta
bright6=8EC07C  # bright cyan
bright7=EBDBB2  # bright white

# cursor needs TWO space-separated RRGGBB values: <cursor-foreground> <cursor-background>
cursor=282828 EBDBB2
selection-foreground=282828
selection-background=D79921


[main]
font=JetBrainsMonoNF :size=10

dpi-aware=yes
pad=6x6


