timeout: 5

interface_resolution: 1920x1080
interface_branding: Arch Linux
term_font_scale: 2x2

/Arch Linux
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: quiet loglevel=3 systemd.show_status=auto rd.udev.log_level=3 vt.global_cursor_default=0 rw
    module_path: boot():/initramfs-linux.img

/Arch Linux (fallback)
    protocol: linux
    path: boot():/vmlinuz-linux
    cmdline: quiet loglevel=3 systemd.show_status=auto rd.udev.log_level=3 vt.global_cursor_default=0 rw
    module_path: boot():/initramfs-linux-fallback.img
