#!/usr/bin/env bash
# ~/.local/bin/update-sway-theme.sh
# Regenerate sway theme from pywal colors

if [ ! -f "$HOME/.cache/wal/colors.sh" ]; then
  echo "pywal colors not found, run wal -i <image> first"
  exit 1
fi

. "$HOME/.cache/wal/colors.sh"

THEME_FILE="$HOME/.config/sway/conf.d/15-theme-colors"

cat >"$THEME_FILE" <<EOF
# Autogenerated by pywal
set \$bg $background
set \$fg $foreground
set \$accent $color4

client.focused          \$accent \$accent \$fg \$accent \$accent
client.unfocused        \$bg \$bg \$fg \$bg \$bg
EOF

swaymsg reload
